CONTIKI_PROJECT = meter-if
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += virtual_meterdev.c
PROJECT_SOURCEFILES += meter-serial.c
PROJECT_SOURCEFILES += meterif_data.c
PROJECT_SOURCEFILES += adc_data.c
PROJECT_SOURCEFILES += debug-uart.c
PROJECT_SOURCEFILES += relay_example.c
PROJECT_SOURCEFILES += lcdlib.c lcd_example.c

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
